version: "3.9"

networks:
  app-net-dev:
    driver: bridge
    name: 'dis_network'

services:
  web-trade:
    container_name: web-trade
    build:
      context: ./
      dockerfile: apps/docker/web/Dockerfile
    expose:
      - 8000
    volumes:
        - ./apps/base/:/app/web/
    networks:
      - app-net-dev

    ports:
        - "7123:8000"
    env_file:
        - apps/.env
    depends_on:
      - db-trade
    restart: unless-stopped

  db-trade:
    image: postgres:16.0
    container_name: db-trade
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - apps/.env
    ports:
      - "5411:5432"
    networks:
      - app-net-dev
    restart: unless-stopped

  celery-trade:
    build:
      context: ./
      dockerfile: apps/docker/web/Dockerfile
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./apps/base/:/app/web/
    networks:
      - app-net-dev
    env_file:
      - apps/.env
    depends_on:
      - web-trade
    restart: unless-stopped

  celery-beat-trade:
    build:
      context: ./
      dockerfile: apps/docker/web/Dockerfile
    command: celery -A app.celery beat --loglevel=info
    volumes:
      - ./apps/base/:/app/web/
    networks:
      - app-net-dev

    env_file:
      - apps/.env
    depends_on:
      - web-trade
      - celery-trade
    restart: unless-stopped

  flower-trade:
    build:
      context: ./
      dockerfile: apps/docker/web/Dockerfile
    command: celery -A app.celery flower
    volumes:
      - ./apps/base/:/app/web/
    depends_on:
      - web-trade
      - celery-trade
      - celery-beat-trade
    networks:
      - app-net-dev
    ports:
      - 4525:5555
    env_file:
      - apps/.env
    restart: unless-stopped

volumes:
  postgres_data:

